### ISSUE TITLE
GPIO value not being set by api

### ISSUE THREAD

**Issue by brendon1555** [marksull/udooneorest#1]
Values are not being correctly set by the API.

I believe value is being overwritten during the valid check within value.rb

```
# Validate the value
value         = ValidateValue.new value
return value.error_message unless value.valid?
```

Possible fix:

```
# Validate the value
value_         = ValidateValue.new value
return value_.error_message unless value_.valid?
```

**Comment by marksull** [comment]
Hey @brendon1555, your observation and fix are both correct. That is what I get for doing a refactor and not testing thoroughly afterwards ;-)

Version 1.0.1 of the GEM pushed with the fix. Just do a "gem update udooneorest".

Cheers
