### ISSUE TITLE
API support for un-exporting gpios

### ISSUE THREAD

**Issue by ddewaele** [marksull/udooneorest#8]
I'm currently working on a [gpio frontend](https://github.com/ddewaele/web-gpio-react) for the UDOO Neo (and other boards)] and I'm using your library.

On the UDOO Neo board, it is also possible to un-export GPIOs.

```
echo 102 > /sys/class/gpio/unexport
```

Would it be possible to implement this on the API ?

**Comment by marksull** [comment]
Didn't know you could unexport ;-) Done. Added in 1.2.0: gem update udooneorest

**Comment by ddewaele** [comment]
Cool ... thx !
