### ISSUE TITLE
thoughts on supporting other boards ?

### ISSUE THREAD

**Issue by ddewaele** [marksull/udooneorest#9]
Any thoughts on supporting other boards ?
- UDOO Dual / Quad
- Raspberry PI
- .... ?

By adding a top level folder 
- http://localhost:4567/udooneo/....
- http://localhost:4567/raspberrypimodelb/....
- http://localhost:4567/udooquad/....

you could support multiple boards with the same API. 

This top-level folder could be used to
- provide board specific gpio pin mappings
- board specific features (like accelerometer / gyro / .... on the UDOO Neo)

Would be happy to help out / define some requirements / test / document ... have most of these board lying around here...

**Comment by marksull** [comment]
We could certainly do that, but I would suggest we create a new project so that we can make it board agnostic (it is named udoo neo rest after all !!)

**Comment by ddewaele** [comment]
renaming a Github repo is surprisingly easy :) Let me know if you would like to discuss it here or through some other app (Gitter / Slack / .....)

**Comment by marksull** [comment]
Added gitter for this repo
